services:
  auto-service-bot:
    image: ghcr.io/yourusername/auto-service-bot:latest
    container_name: auto-service-bot
    restart: unless-stopped

    # Environment variables - use .env file or environment
    env_file:
      - .env

    # Security settings
    user: "1000:1000"

    # Port mapping (only needed for webhook mode)
    ports:
      - "${WEBHOOK_PORT:-3000}:3000"

    # Volume mounts for persistence and configuration
    volumes:
      - ./data:/app/data:ro
      - ./config/system-prompt.md:/app/config/system-prompt.md:ro
      - ./config/welcome-message.md:/app/config/welcome-message.md:ro

    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-f", "ruby bot.rb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Redis for session storage (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   container_name: auto-service-bot-redis
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data
  #   command: redis-server --appendonly yes
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

# Uncomment if using Redis
# volumes:
#   redis_data:
